import { fetchWrapper } from './util/fetchWrapper';
import { sign } from './sign';
import { NFTResult } from './types';
import { checkApiKey, checkMetamask } from './util/checks';

export type NFTPassVerifyParams = {
    /**
     * Api Key for corresponding configuration from admin page
     */
    apiKey: string,
    /**
     *  message to be signed in wallet, uses generic message by default
     *  (can be omitted, if jwt is passed)
     */
    message?: string,
    /**
     * json web token, generated by authentication method.
     * If passed,
     */
    jwt?:string,
};

export type NFTPassVerifyData = {
    /**
     * if there are matching nfts for the selected wallet on configured network
     */
    match: boolean,
    /**
     * which network was used for nfts search
     */
    network: string,
    /**
     *  list of NFTS, owned by the wallet, that matched Application configuration
     */
    nfts: NFTResult[]
}

export async function verify(
    {
        apiKey,
        message,
        jwt
    }: NFTPassVerifyParams = { apiKey: null }): Promise<NFTPassVerifyData> {
    checkApiKey(apiKey);
    checkMetamask();
    return await fetchWrapper(apiKey, '/api/client/verify', jwt ? {jwt} : await sign(message));
}
